[build]
  base = "kc-web-design"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "https://web-kenchase.netlify.app/*"
  to = "https://web.kenchase.com/:splat"
  status = 301
  force = true
